stages:
    example:
        cmd: papermill --log-output --stdout-file /dev/stdout seam_carving.ipynb /dev/null
        deps:
            - data/source.jpg
        outs:
            - data/target.jpg
            - data/process.gif
        params:
            - n_shrink
            - downsize
            - gif
